# À modifier avec le nom et la description du site
site_name: "SIO 1 maths approfondissement"
site_description: Un modèle avec pyodide-mkdocs-theme

# À modifier, avec votre nom et la licence choisie
copyright: |
    Mireille Coilhac
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>.
    <br><a href="https://aeif.fr">Design by AEIF</a>

# À modifier, avec votre mail
#extra:
    #social:
        #- icon: fontawesome/regular/envelope
          #link: mailto:votre.mail@ac-academie.fr
          #name: Écrire à l'auteur
        #- icon: fontawesome/brands/gitlab
          #link: !ENV [CI_PROJECT_ROOT_NAMESPACE]
          #name: AEIF

# Éventuellement à modifier avec votre thème de couleurs
theme:
    favicon: favicon.png
    logo: math.png
    name: pyodide-mkdocs-theme

    features:
        #- navigation.instant
        #- navigation.tabs   Pour avoir le menu vertical il fallait supprimer ça
        - navigation.top
        - toc.integrate
        - header.autohide
        - content.code.annotate   # Pour les annotations de code deroulantes avec +
        - content.code.copy  # Ajout après MAJ pour pouvoir copier du code



site_url: !ENV [CI_PAGES_URL, "http://127.0.0.1:8000/"]
site_author: !ENV [CI_COMMIT_AUTHOR, "Nom d'auteur"]
repo_url: !ENV [CI_PROJECT_URL]
edit_uri: !ENV [EDIT_VARIABLE]

docs_dir: docs

#nav:   inutile on utilise les fichiers .pages plus pratiques

markdown_extensions:
    - md_in_html
    - meta
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        auto_title: true
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji: # Émojis  :boom:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 2


plugins:

  - awesome-pages:   # Pour les fichiers .pages
      collapse_single_pages: true

  - material/search
  - material/tags:
      tags_file: tags.md
  - pyodide_macros:
      # Vous pouvez ajouter ici tout réglage que vous auriez ajouté concernant les macros:
      on_error_fail: true     # Il est conseillé d'ajouter celui-ci si vous ne l'utilisez pas.
      build:
        python_libs:
          - turtle
        tab_to_spaces: 4


# En remplacement de mkdocs-exclude. Tous les fichiers correspondant aux patterns indiqués seront
# exclu du site final et donc également de l'indexation de la recherche.
# Nota: ne pas mettre de commentaires dans ces lignes !
exclude_docs: |
    **/*_REM.md
    **/*.py

#extra_javascript:  Supprimé pour MAJ pyodide pris en compte par le thème lui même
  #- xtra/mathjax.js                    # MathJax
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - xtra/stylesheets/ajustements.css  # ajustements
